# Generated by Django 5.2.14 on 2026-06-02 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-префикс')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ИИ-инструмента')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание / Инструкция')),
                ('prompt_text', models.TextField(blank=True, null=True, verbose_name='Готовый промпт (если есть)')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на сервис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'ИИ Инструмент',
                'verbose_name_plural': 'ИИ Инструменты',
            },
        ),
    ]
