# Generated by Django 5.2.14 on 2026-06-03 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aitool_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aitool',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонен'), ('hidden', 'Скрыт')], default='published', max_length=20, verbose_name='Статус публикации'),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='admin_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_author_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('reviewing', 'На рассмотрении'), ('approved', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'Приостановлен')], default='active', max_length=20)),
                ('revenue_share_percent', models.PositiveSmallIntegerField(default=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_author_profiles', to='main.authorapplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
