# Generated by Django 5.2.14 on 2026-06-03 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aitool_author_aitool_publication_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=80)),
                ('task', models.TextField()),
                ('tone', models.CharField(max_length=80)),
                ('language', models.CharField(max_length=40)),
                ('output_format', models.CharField(max_length=80)),
                ('generated_prompt', models.TextField()),
                ('provider', models.CharField(default='template', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_generations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
