from django.core.management.base import BaseCommand
from django.utils.text import slugify

from main.management.commands.seed_categories import CATEGORY_TREE
from main.models import AITool, Category


TOOLS = [
    {
        "title": "ChatGPT",
        "seo_slug": "chatgpt",
        "category": "Промпты для анализа Excel/CSV отчетов",
        "audience": AITool.Audience.FOUNDERS,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "Универсальный AI-ассистент для анализа данных, текстов, документов и рабочих сценариев.",
        "problem_solved": "Помогает быстро разбирать таблицы, писать отчеты, готовить идеи и структурировать задачи.",
        "full_description": "ChatGPT подходит как базовый AI-инструмент для команды: анализирует файлы, помогает с текстами, кодом, исследованиями, финансовыми выкладками и внутренними документами.",
        "external_link": "https://chatgpt.com/",
        "time_saving_hours": 6,
        "setup_minutes": 10,
        "price_usd": "0.00",
        "is_featured": True,
    },
    {
        "title": "Claude",
        "seo_slug": "claude",
        "category": "Подготовка и редактура документов",
        "audience": AITool.Audience.FOUNDERS,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-ассистент для длинных документов, аналитики, черновиков и сложных текстовых задач.",
        "problem_solved": "Ускоряет работу с большими текстами, договоренностями, исследованиями и внутренними материалами.",
        "full_description": "Claude полезен для анализа документов, подготовки резюме, сравнения вариантов, редактуры и аккуратной работы с большими объемами текста.",
        "external_link": "https://claude.ai/",
        "time_saving_hours": 5,
        "setup_minutes": 10,
        "price_usd": "0.00",
        "is_featured": True,
    },
    {
        "title": "Google Gemini",
        "seo_slug": "google-gemini",
        "category": "Промпты для анализа Excel/CSV отчетов",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI от Google для поиска, анализа, работы с текстами и задачами в экосистеме Google.",
        "problem_solved": "Помогает быстрее готовить исследования, письма, таблицы и рабочие материалы.",
        "full_description": "Gemini удобно использовать компаниям, которые уже работают в Google Workspace и хотят добавить AI в документы, почту, таблицы и ресерч.",
        "external_link": "https://gemini.google.com/",
        "time_saving_hours": 4,
        "setup_minutes": 10,
        "price_usd": "0.00",
    },
    {
        "title": "Microsoft 365 Copilot",
        "seo_slug": "microsoft-365-copilot",
        "category": "Автоматизация внутренней базы знаний компании",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI в Word, Excel, PowerPoint, Outlook и Teams для офисной работы.",
        "problem_solved": "Сокращает время на документы, встречи, письма, презентации и сводки.",
        "full_description": "Microsoft 365 Copilot подходит командам, которые живут в Microsoft 365 и хотят встроить AI в ежедневный документооборот и коммуникации.",
        "external_link": "https://www.microsoft.com/microsoft-365/copilot",
        "time_saving_hours": 7,
        "setup_minutes": 60,
        "price_usd": "30.00",
        "is_featured": True,
    },
    {
        "title": "Tableau Agent",
        "seo_slug": "tableau-agent",
        "category": "Промпты для анализа Excel/CSV отчетов",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI-помощник для аналитики и вопросов к данным внутри Tableau.",
        "problem_solved": "Помогает быстрее строить инсайты, объяснять графики и находить ответы в данных.",
        "full_description": "Tableau Agent полезен аналитикам и руководителям, которым нужно быстрее получать выводы из BI-дашбордов и данных компании.",
        "external_link": "https://www.tableau.com/products/tableau-agent",
        "time_saving_hours": 5,
        "setup_minutes": 90,
        "price_usd": "0.00",
    },
    {
        "title": "Domo AI",
        "seo_slug": "domo-ai",
        "category": "Промпты для анализа Excel/CSV отчетов",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI-функции для BI, дашбордов, data apps и операционной аналитики.",
        "problem_solved": "Ускоряет принятие решений на основе данных и автоматизирует аналитику.",
        "full_description": "Domo AI подходит компаниям, которым нужна единая BI-платформа с AI-поиском, автоматизацией и визуализацией данных.",
        "external_link": "https://www.domo.com/",
        "time_saving_hours": 5,
        "setup_minutes": 120,
        "price_usd": "0.00",
    },
    {
        "title": "Jasper",
        "seo_slug": "jasper",
        "category": "Создание рекламных креативов и копирайтинг",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-платформа для маркетинговых текстов, кампаний и брендового контента.",
        "problem_solved": "Помогает быстрее выпускать тексты для рекламы, email, лендингов и соцсетей.",
        "full_description": "Jasper полезен маркетинговым командам, которым нужно сохранять tone of voice бренда и масштабировать производство контента.",
        "external_link": "https://www.jasper.ai/",
        "time_saving_hours": 6,
        "setup_minutes": 30,
        "price_usd": "39.00",
        "is_featured": True,
    },
    {
        "title": "Copy.ai",
        "seo_slug": "copy-ai",
        "category": "Создание рекламных креативов и копирайтинг",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI для маркетинговых и sales-текстов, писем, сценариев и кампаний.",
        "problem_solved": "Снимает рутину с написания черновиков и вариантов рекламных сообщений.",
        "full_description": "Copy.ai можно использовать для генерации рекламных сообщений, холодных писем, описаний продуктов и контентных заготовок.",
        "external_link": "https://www.copy.ai/",
        "time_saving_hours": 4,
        "setup_minutes": 20,
        "price_usd": "0.00",
    },
    {
        "title": "HubSpot AI",
        "seo_slug": "hubspot-ai",
        "category": "Квалификация лидов и холодные рассылки",
        "audience": AITool.Audience.SALES,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI-функции в CRM для маркетинга, продаж, писем, контента и поддержки.",
        "problem_solved": "Связывает лиды, CRM-данные, письма и контент в один рабочий процесс.",
        "full_description": "HubSpot AI подходит малому и среднему бизнесу, который хочет усилить CRM, email-маркетинг, sales outreach и клиентский сервис.",
        "external_link": "https://www.hubspot.com/artificial-intelligence",
        "time_saving_hours": 6,
        "setup_minutes": 90,
        "price_usd": "0.00",
    },
    {
        "title": "Perplexity",
        "seo_slug": "perplexity",
        "category": "SEO-оптимизация и написание статей",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-поиск для ресерча рынка, конкурентов, тем и источников.",
        "problem_solved": "Ускоряет исследование тем, конкурентов, фактов и идей для контента.",
        "full_description": "Perplexity удобно использовать перед подготовкой статей, PR-материалов, аналитических заметок и конкурентных обзоров.",
        "external_link": "https://www.perplexity.ai/",
        "time_saving_hours": 4,
        "setup_minutes": 10,
        "price_usd": "0.00",
    },
    {
        "title": "Intercom Fin",
        "seo_slug": "intercom-fin",
        "category": "AI-ассистенты для поддержки клиентов (чат-боты)",
        "audience": AITool.Audience.SALES,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.AGENT,
        "short_description": "AI-агент поддержки, который отвечает клиентам на основе базы знаний.",
        "problem_solved": "Снижает нагрузку на поддержку и ускоряет ответы на типовые вопросы.",
        "full_description": "Intercom Fin подходит сервисным командам, которые хотят автоматизировать первую линию поддержки и сохранить контроль над качеством ответов.",
        "external_link": "https://www.intercom.com/fin",
        "time_saving_hours": 8,
        "setup_minutes": 120,
        "price_usd": "0.99",
        "is_featured": True,
    },
    {
        "title": "Zendesk AI",
        "seo_slug": "zendesk-ai",
        "category": "AI-ассистенты для поддержки клиентов (чат-боты)",
        "audience": AITool.Audience.SALES,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI для тикетов, саппорта, маршрутизации и клиентских ответов.",
        "problem_solved": "Помогает быстрее обрабатывать обращения и масштабировать службу поддержки.",
        "full_description": "Zendesk AI полезен компаниям с потоком обращений, где важны triage, база знаний, макросы и аналитика качества поддержки.",
        "external_link": "https://www.zendesk.com/ai/",
        "time_saving_hours": 7,
        "setup_minutes": 120,
        "price_usd": "0.00",
    },
    {
        "title": "Salesforce Agentforce",
        "seo_slug": "salesforce-agentforce",
        "category": "Квалификация лидов и холодные рассылки",
        "audience": AITool.Audience.SALES,
        "difficulty": AITool.Difficulty.ADVANCED,
        "product_type": AITool.ProductType.AGENT,
        "short_description": "AI-агенты Salesforce для CRM, продаж, сервиса и автоматизации задач.",
        "problem_solved": "Автоматизирует CRM-сценарии вокруг лидов, клиентов, сделок и обращений.",
        "full_description": "Agentforce подойдет зрелым sales и service-командам, которые уже используют Salesforce и хотят запускать AI-агентов поверх CRM-данных.",
        "external_link": "https://www.salesforce.com/agentforce/",
        "time_saving_hours": 8,
        "setup_minutes": 180,
        "price_usd": "0.00",
    },
    {
        "title": "Clari",
        "seo_slug": "clari",
        "category": "Квалификация лидов и холодные рассылки",
        "audience": AITool.Audience.SALES,
        "difficulty": AITool.Difficulty.ADVANCED,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "Revenue intelligence для прогнозов продаж, pipeline и управления выручкой.",
        "problem_solved": "Повышает точность прогноза продаж и помогает видеть риски в pipeline.",
        "full_description": "Clari полезен B2B-командам продаж, где нужно управлять forecast, сделками, активностями и сигналами по выручке.",
        "external_link": "https://www.clari.com/",
        "time_saving_hours": 6,
        "setup_minutes": 180,
        "price_usd": "0.00",
    },
    {
        "title": "GitHub Copilot",
        "seo_slug": "github-copilot",
        "category": "Генерация и аудит кода, написание технической документации",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-ассистент для написания, объяснения, тестирования и рефакторинга кода.",
        "problem_solved": "Ускоряет разработку, ревью, автодополнение и работу с типовыми задачами.",
        "full_description": "GitHub Copilot подходит разработчикам и IT-командам, которым нужен ассистент прямо в IDE и GitHub.",
        "external_link": "https://github.com/features/copilot",
        "time_saving_hours": 6,
        "setup_minutes": 20,
        "price_usd": "10.00",
        "is_featured": True,
    },
    {
        "title": "Cursor",
        "seo_slug": "cursor",
        "category": "Генерация и аудит кода, написание технической документации",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI IDE для разработки, навигации по проекту и изменений в кодовой базе.",
        "problem_solved": "Помогает быстрее понимать проект, писать код и вносить связанные изменения.",
        "full_description": "Cursor удобен для команд, которым нужен AI-редактор с контекстом всего проекта, чатом по коду и генерацией изменений.",
        "external_link": "https://www.cursor.com/",
        "time_saving_hours": 7,
        "setup_minutes": 30,
        "price_usd": "0.00",
    },
    {
        "title": "Codex",
        "seo_slug": "codex",
        "category": "Генерация и аудит кода, написание технической документации",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.AGENT,
        "short_description": "AI-агент для разработки, исправления кода, тестов и работы с репозиторием.",
        "problem_solved": "Берет на себя инженерные задачи от анализа до внесения и проверки изменений.",
        "full_description": "Codex полезен там, где нужен не только чат, а агентная работа с файлами, тестами, ошибками и локальным проектом.",
        "external_link": "https://openai.com/codex/",
        "time_saving_hours": 8,
        "setup_minutes": 20,
        "price_usd": "0.00",
    },
    {
        "title": "Snyk AI",
        "seo_slug": "snyk-ai",
        "category": "Генерация и аудит кода, написание технической документации",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI-помощь для поиска, объяснения и исправления уязвимостей в коде.",
        "problem_solved": "Снижает риск уязвимостей и ускоряет remediation в разработке.",
        "full_description": "Snyk AI подходит IT-командам, которые хотят встроить security checks и подсказки по исправлениям в developer workflow.",
        "external_link": "https://snyk.io/",
        "time_saving_hours": 5,
        "setup_minutes": 60,
        "price_usd": "0.00",
    },
    {
        "title": "Notion AI",
        "seo_slug": "notion-ai",
        "category": "Автоматизация внутренней базы знаний компании",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI внутри Notion для базы знаний, документов, планов и рабочих заметок.",
        "problem_solved": "Помогает поддерживать порядок в знаниях, задачах, планах и документах команды.",
        "full_description": "Notion AI подходит командам, которые ведут процессы, знания и проекты в Notion и хотят быстрее писать, искать и резюмировать информацию.",
        "external_link": "https://www.notion.com/product/ai",
        "time_saving_hours": 4,
        "setup_minutes": 20,
        "price_usd": "10.00",
    },
    {
        "title": "Glean",
        "seo_slug": "glean",
        "category": "Автоматизация внутренней базы знаний компании",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.ADVANCED,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "Корпоративный AI-поиск и ассистент по внутренним данным компании.",
        "problem_solved": "Помогает сотрудникам находить ответы по документам, чатам, таскам и базе знаний.",
        "full_description": "Glean полезен растущим командам с большим количеством внутренних источников знаний и повторяющихся вопросов.",
        "external_link": "https://www.glean.com/",
        "time_saving_hours": 7,
        "setup_minutes": 180,
        "price_usd": "0.00",
    },
    {
        "title": "Workday AI",
        "seo_slug": "workday-ai",
        "category": "Скрининг резюме и генерация вопросов для собеседований",
        "audience": AITool.Audience.HR,
        "difficulty": AITool.Difficulty.ADVANCED,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI-функции Workday для HR, people analytics, навыков и кадровых процессов.",
        "problem_solved": "Помогает HR-командам быстрее работать с данными сотрудников и процессами найма.",
        "full_description": "Workday AI подходит компаниям, где HR-процессы уже построены вокруг Workday и нужны прогнозы, рекомендации и автоматизация.",
        "external_link": "https://www.workday.com/",
        "time_saving_hours": 5,
        "setup_minutes": 180,
        "price_usd": "0.00",
    },
    {
        "title": "Canva AI",
        "seo_slug": "canva-ai",
        "category": "Дизайн презентаций и макетов",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-инструменты Canva для дизайна, презентаций, баннеров, видео и бренд-материалов.",
        "problem_solved": "Позволяет быстро собирать визуалы без отдельной дизайн-команды.",
        "full_description": "Canva AI полезен маркетингу, founders и HR для быстрых презентаций, соцсетей, баннеров и визуальных материалов.",
        "external_link": "https://www.canva.com/ai/",
        "time_saving_hours": 5,
        "setup_minutes": 15,
        "price_usd": "0.00",
        "is_featured": True,
    },
    {
        "title": "Adobe Firefly",
        "seo_slug": "adobe-firefly",
        "category": "Генерация изображений и бренд-креативов",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "Генеративный AI Adobe для изображений, эффектов, графики и креативов.",
        "problem_solved": "Ускоряет создание визуальных вариантов и брендовых материалов.",
        "full_description": "Adobe Firefly подходит маркетологам и дизайнерам, которым нужны визуалы, text effects и AI-функции внутри Adobe-экосистемы.",
        "external_link": "https://www.adobe.com/products/firefly.html",
        "time_saving_hours": 4,
        "setup_minutes": 20,
        "price_usd": "0.00",
    },
    {
        "title": "Midjourney",
        "seo_slug": "midjourney",
        "category": "Генерация изображений и бренд-креативов",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-генератор изображений для концептов, рекламы, стиля и креативных направлений.",
        "problem_solved": "Помогает быстро искать визуальные идеи и создавать качественные концепты.",
        "full_description": "Midjourney полезен для moodboards, рекламных образов, иллюстраций, визуальных направлений и креативных гипотез.",
        "external_link": "https://www.midjourney.com/",
        "time_saving_hours": 4,
        "setup_minutes": 30,
        "price_usd": "10.00",
    },
    {
        "title": "Runway",
        "seo_slug": "runway",
        "category": "Создание видео и аватаров",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-платформа для генерации, редактирования и продакшена видео.",
        "problem_solved": "Ускоряет производство видео-креативов и прототипов роликов.",
        "full_description": "Runway подходит маркетингу и креативным командам, которым нужно быстро создавать видеоролики, правки, эффекты и раскадровки.",
        "external_link": "https://runwayml.com/",
        "time_saving_hours": 5,
        "setup_minutes": 30,
        "price_usd": "0.00",
    },
    {
        "title": "HeyGen",
        "seo_slug": "heygen",
        "category": "Создание видео и аватаров",
        "audience": AITool.Audience.SMM,
        "difficulty": AITool.Difficulty.BEGINNER,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-видео с аватарами, озвучкой и локализацией для обучения и маркетинга.",
        "problem_solved": "Позволяет быстро делать видео без съемочной команды.",
        "full_description": "HeyGen полезен для обучающих роликов, onboarding-видео, sales enablement, продуктовых объяснений и локализации контента.",
        "external_link": "https://www.heygen.com/",
        "time_saving_hours": 5,
        "setup_minutes": 30,
        "price_usd": "0.00",
    },
    {
        "title": "Zapier AI",
        "seo_slug": "zapier-ai",
        "category": "Автоматизация бизнес-процессов и workflow",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI и no-code автоматизация между приложениями, CRM, таблицами и коммуникациями.",
        "problem_solved": "Убирает ручные переносы данных и связывает сервисы в повторяемые процессы.",
        "full_description": "Zapier AI подходит командам, которым нужно быстро автоматизировать действия между SaaS-инструментами без отдельной разработки.",
        "external_link": "https://zapier.com/ai",
        "time_saving_hours": 6,
        "setup_minutes": 60,
        "price_usd": "0.00",
    },
    {
        "title": "Make AI",
        "seo_slug": "make-ai",
        "category": "Автоматизация бизнес-процессов и workflow",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "Визуальная автоматизация процессов с AI-блоками и интеграциями.",
        "problem_solved": "Помогает строить сложные сценарии между сервисами и данными.",
        "full_description": "Make AI полезен операционным командам, которые хотят гибко автоматизировать процессы, уведомления, CRM, таблицы и AI-обработку данных.",
        "external_link": "https://www.make.com/",
        "time_saving_hours": 6,
        "setup_minutes": 90,
        "price_usd": "0.00",
    },
    {
        "title": "n8n AI",
        "seo_slug": "n8n-ai",
        "category": "AI-агенты для интеграций",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.ADVANCED,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "Workflow automation с AI-агентами, интеграциями и self-hosted сценариями.",
        "problem_solved": "Дает гибкую автоматизацию для команд, которым важен контроль над процессами и данными.",
        "full_description": "n8n AI подходит техническим и операционным командам для построения автоматизаций, агентов, webhooks и интеграций вокруг внутренних систем.",
        "external_link": "https://n8n.io/",
        "time_saving_hours": 7,
        "setup_minutes": 120,
        "price_usd": "0.00",
    },
    {
        "title": "Harvey",
        "seo_slug": "harvey",
        "category": "Анализ договоров и юридических рисков",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.ADVANCED,
        "product_type": AITool.ProductType.MINI_SERVICE,
        "short_description": "AI-платформа для юридического анализа, правового ресерча и документов.",
        "problem_solved": "Ускоряет юридический ресерч и подготовку рабочих документов.",
        "full_description": "Harvey ориентирован на юридические команды и компании, которым нужна AI-помощь в анализе договоров, ресерче и профессиональном документообороте.",
        "external_link": "https://www.harvey.ai/",
        "time_saving_hours": 6,
        "setup_minutes": 120,
        "price_usd": "0.00",
    },
    {
        "title": "Spellbook",
        "seo_slug": "spellbook",
        "category": "Анализ договоров и юридических рисков",
        "audience": AITool.Audience.OPERATIONS,
        "difficulty": AITool.Difficulty.MIDDLE,
        "product_type": AITool.ProductType.INTEGRATION,
        "short_description": "AI для проверки, составления и редактирования договоров.",
        "problem_solved": "Помогает быстрее находить риски, править формулировки и готовить договоры.",
        "full_description": "Spellbook полезен юристам и операционным командам, которые часто работают с договорами и хотят ускорить review без потери контроля.",
        "external_link": "https://www.spellbook.legal/",
        "time_saving_hours": 5,
        "setup_minutes": 60,
        "price_usd": "0.00",
    },
]


class Command(BaseCommand):
    help = "Creates curated existing AI tools for the catalog."

    def _build_unique_slug(self, base_text):
        base_slug = slugify(base_text, allow_unicode=True)[:40] or "category"
        candidate = base_slug
        idx = 2
        while Category.objects.filter(slug=candidate).exists():
            suffix = f"-{idx}"
            candidate = f"{base_slug[:40-len(suffix)]}{suffix}"
            idx += 1
        return candidate

    def _ensure_categories(self):
        for parent_item in CATEGORY_TREE:
            parent = Category.objects.filter(name=parent_item["name"], parent__isnull=True).first()
            if not parent:
                parent = Category.objects.create(
                    name=parent_item["name"],
                    slug=self._build_unique_slug(parent_item["name"]),
                    icon_emoji=parent_item["icon"],
                    description=parent_item["description"],
                )
            else:
                parent.icon_emoji = parent_item["icon"]
                parent.description = parent_item["description"]
                parent.parent = None
                parent.save(update_fields=["icon_emoji", "description", "parent"])

            for child_name in parent_item["children"]:
                Category.objects.get_or_create(
                    name=child_name,
                    parent=parent,
                    defaults={
                        "slug": self._build_unique_slug(f"{parent_item['name']}-{child_name}"),
                        "icon_emoji": "",
                        "description": "",
                    },
                )

    def handle(self, *args, **options):
        self._ensure_categories()
        created = 0
        updated = 0

        for item in TOOLS:
            category = Category.objects.filter(name=item["category"]).first()
            if not category:
                self.stderr.write(self.style.WARNING(f"Category not found: {item['category']}"))
                continue

            defaults = {key: value for key, value in item.items() if key not in {"seo_slug", "category"}}
            defaults["category"] = category

            _, was_created = AITool.objects.update_or_create(
                seo_slug=item["seo_slug"],
                defaults=defaults,
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(f"Done. Created: {created}, Updated: {updated}"))
